[build]
  base = "."
  command = "vite build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "dist/public/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 5000
