[build]
  base = "."
  command = "vite build"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 5000

[build]
  command = "vite build"
  external = ["@rollup/rollup-linux-x64-gnu"]